interface Env {
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  OAUTH_REDIRECT_URI: string;
  GSC_SITE_URL: string;
  BRANDED_KEYWORDS?: string;
  BUSINESS_UNIT_KEYWORDS_JSON?: string;
  SESSION_SECRET?: string;
  TIKTOK_ACCESS_TOKEN?: string;
  TIKTOK_REFRESH_TOKEN?: string;
  TIKTOK_ANALYTICS_ENDPOINT?: string;
  TIKTOK_CLIENT_KEY?: string;
  TIKTOK_CLIENT_SECRET?: string;
  TIKTOK_OPEN_ID?: string;
  TIKTOK_FOLLOWER_HISTORY_URL?: string;
  TIKTOK_OAUTH_REDIRECT_URI?: string;
  TIKTOK_FOLLOWERS_KV?: KVNamespace;
  TIKTOK_SNAPSHOT_SECRET?: string;
}
